### ISSUE TITLE
[User Story] Game Library

### ISSUE THREAD

**Issue by larevolucia** [larevolucia/my-test-repository#8]
As a casual gamer, I want to know what games are available so I can decide if I want to book a time to visit the shop.

**Acceptance criteria:**

- [x] The website has a separate page for the list of board games.
- [x] The boardgame library page utilises the Bootstrap grid and card components for consistency in layout and responsiveness
- [x] Each card states the relevant game title, image, descriptions, number of players and age range

**Tasks**

- [x] Create a Library HTML and link it to navbar
- [x] Create content cards using bootstrap to display games in carousel mode
- [x] Ensure design is responsive and functions in all screen sizes
