### ISSUE TITLE
[User Story] Game Reservation form

### ISSUE THREAD

**Issue by larevolucia** [larevolucia/my-test-repository#9]
As a game enthusiast I want to be able to reserve the game I'm interested so I guarantee that it will be available for me.

**Acceptance Criteria**:

- [x] Form is available to reserve games displayed on the Game Library page
- [x] The user can fill out their selected game, name, contact information, and preferred date for the reservation.

**Task**:

- [x] Create form to reserve games. For shoudl contain Gamer name, e-mail, date and time for the booking and the game selected
- [x] Ensure design is responsive and functions in all screen sizes
